global:
  logging:
    - type: syslog
      level: info
      format: human

jobs:
  - name: local_snapshots
    type: snap
    filesystems: {
      "tank/nextcloud-app": true,
      "tank/nextcloud-sync": true,
      "tank/nextcloud-collab": true,
      "tank/nextcloud-db": true,
      "tank/nextcloud-redis": true,
      "tank/backups": true
    }
    snapshotting:
      type: periodic
      interval: 1h
      prefix: autosnap_
    pruning:
      keep:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 14x1d | 12x1w
          regex: "^autosnap_"
        - type: regex
          negate: true
          regex: "^autosnap_"

  - name: push_to_nas02
    type: push
    connect:
      type: ssh+stdinserver
      host: nas02.outliertechnology.co.uk
      user: zrepl
      port: 22
      identity_file: /etc/zrepl/keys/id_ed25519_zrepl_nas01
    filesystems: {
      "tank/nextcloud-app": true,
      "tank/nextcloud-sync": true,
      "tank/nextcloud-collab": true,
      "tank/nextcloud-db": true,
      "tank/nextcloud-redis": true,
      "tank/backups": true
    }
    snapshotting:
      type: manual
    send:
      encrypted: false
    replication:
      protection:
        initial: guarantee_resumability
        incremental: guarantee_incremental
    pruning:
      keep_sender:
        - type: regex
          regex: ".*"
      keep_receiver:
        - type: grid
          grid: 1x1h(keep=all) | 24x1h | 360x1d
          regex: "^autosnap_"
        - type: regex
          negate: true
          regex: "^autosnap_"

